from __future__ import annotations

from copy import deepcopy
from typing import Any

DEFAULT_LOCALE = "zh-CN"

COMMON_UI: dict[str, Any] = {
    "app_name": "Persona Distiller",
    "brand_name": "角色蒸馏台",
    "brand_tagline": "本地语料控制台",
    "nav_projects": "项目",
    "nav_settings": "设置",
    "back_to_project": "返回项目",
    "back_to_analysis": "返回分析",
    "back_to_assets": "返回资产",
    "open_playground": "进入试聊",
    "open_preprocess": "进入预分析",
    "save": "保存",
    "cancel": "取消",
    "delete": "删除",
    "edit": "编辑",
    "close": "关闭",
    "details": "详情",
    "view": "查看",
    "retry": "重试",
    "refresh": "刷新",
    "loading": "加载中…",
    "request_failed": "请求失败",
    "unknown_error": "发生未知错误，请稍后再试。",
    "empty_state": "暂无内容",
    "created_at": "创建时间",
    "updated_at": "更新时间",
    "confirm_continue": "确认继续吗？",
    "confirm_delete_project": "确定删除这个项目及其相关数据吗？此操作不可恢复。",
    "confirm_delete_document": "确定删除这份文档吗？此操作不可恢复。",
    "confirm_delete_session": "确定删除这个会话吗？",
    "confirm_delete_profile": "确定删除这个画像吗？",
}

PAGE_UI: dict[str, dict[str, Any]] = {
    "index": {
        "title": "项目总览",
        "eyebrow": "项目总览控制台",
        "hero_title": "把语料、分析、资产和试聊放进同一个控制台",
        "hero_note": "保留 FastAPI + Jinja + 原生 JS 架构，在不引入新前端框架的前提下，统一管理上传、处理、分析、资产生成与试聊验证。",
        "metric_projects": "项目数量",
        "metric_note": "当前工作区内已创建的项目总数",
        "panel_create": "创建新项目",
        "panel_existing": "最近项目",
        "create_name": "项目名称",
        "create_name_placeholder": "例如：Alice、创始人访谈、旅行群聊画像",
        "create_mode": "工作模式",
        "mode_group": "群组模式",
        "mode_group_hint": "适合群聊、社群、团队等多角色语料",
        "mode_single": "单人模式",
        "mode_single_hint": "适合单个人物、作者、主播或品牌人格",
        "create_description": "项目说明",
        "create_description_placeholder": "说明语料来源、目标角色，以及需要重点保留的表达方式。",
        "create_submit": "创建项目",
        "empty_projects": "还没有项目，先创建一个开始搭建你的控制台。",
        "status_chat_ready": "Chat LLM 已就绪",
        "status_chat_missing": "Chat LLM 未配置",
        "status_embedding_ready": "Embedding 已就绪",
        "status_embedding_missing": "Embedding 未配置，将回退到词法检索",
        "project_card_open": "打开项目",
        "project_card_edit": "编辑项目",
        "project_card_delete": "删除项目",
        "project_description_empty": "暂无项目说明",
        "project_updated": "最近更新",
        "modal_edit_title": "编辑项目",
        "modal_name": "项目名称",
        "modal_description": "项目说明",
        "modal_mode": "工作模式",
        "modal_submit": "保存修改",
    },
    "project": {
        "title": "项目控制台",
        "eyebrow": "项目控制中心",
        "upload_title": "语料上传与处理",
        "upload_hint": "拖拽或选择文件后可直接批量处理，文档状态和任务进度会自动刷新。",
        "dropzone_title": "拖拽文件到这里，或点击选择文档",
        "dropzone_note": "支持 html、json、jsonl、docx、pdf、txt、md、log",
        "analysis_title": "分析配置",
        "analysis_target_role": "目标角色",
        "analysis_context": "分析上下文",
        "analysis_concurrency": "分析并发",
        "analysis_submit_disabled": "需要先处理可分析文档",
        "analysis_submit": "启动分析",
        "analysis_help": "这些配置会进入检索、分析和资产合成流程。",
        "analysis_group_note": "群组模式请先创建画像，再按画像分别启动分析。",
        "group_profiles": "群组画像",
        "group_profiles_empty": "还没有群组成员画像，先添加一个角色。",
        "add_profile": "添加画像",
        "profile_name": "角色名称",
        "profile_description": "角色说明",
        "profile_submit": "保存画像",
        "profile_delete_confirm": "确定删除这个画像吗？",
        "profile_view_analysis": "查看分析",
        "profile_view_asset": "查看资产",
        "profile_run_analysis": "生成分析",
        "document_panel": "文档处理看板",
        "document_empty": "当前项目还没有文档。",
        "document_load_more": "加载更多",
        "document_filter_all": "全部",
        "document_filter_ready": "可分析",
        "document_filter_active": "处理中",
        "document_filter_failed": "失败",
        "refresh_documents": "刷新列表",
        "process_all": "一键处理",
        "retry_all": "失败重试",
        "stop_processing": "停止处理",
        "stats_total": "文档总数",
        "stats_ready": "可分析",
        "stats_pending": "待处理",
        "stats_failed": "失败",
        "modal_document_title": "文档详情",
        "modal_process_document": "处理此文档",
        "modal_retry_document": "重新处理",
        "modal_save_document": "保存文档信息",
        "modal_edit_project": "编辑项目",
        "modal_add_profile": "添加群组画像",
        "workspace_mode": "工作模式",
        "single_mode": "单人模式",
        "group_mode": "群组模式",
        "no_project_description": "这个项目还没有说明，你可以补充语料背景和目标角色。",
        "latest_analysis": "最新分析",
        "not_analyzed": "尚未分析",
        "latest_release": "最新发布",
        "unreleased": "尚未发布",
        "queued": "已排队",
        "processing": "处理中",
        "ready": "可分析",
        "failed": "失败",
        "unprocessed": "未处理",
        "upload_success": "文档上传完成。",
        "upload_empty": "请先选择至少一个文件。",
        "uploading": "正在上传文档…",
        "process_success": "任务已加入处理队列。",
        "retry_success": "失败文档已重新加入处理队列。",
        "stop_success": "当前项目的处理任务已停止。",
        "document_save_success": "文档信息已保存。",
        "document_delete_success": "文档已删除。",
        "document_filename": "文件名",
        "document_status": "状态",
        "document_source_type": "来源类型",
        "document_language": "语言",
        "document_note": "备注",
        "document_error": "错误信息",
        "document_task_stage": "任务阶段",
        "document_progress": "处理进度",
        "document_open": "查看详情",
        "document_delete": "删除文档",
        "document_queued_hint": "处理中队列会自动推送最新状态。",
        "child_project_hint": "子画像项目沿用父项目文档，请返回群组项目管理语料。",
        "profile_description_empty": "暂无画像说明",
    },
    "analysis": {
        "title": "分析监控",
        "eyebrow": "分析运行监控",
        "hero_note": "实时查看队列、槽位占用、最新事件、LLM 成功与回退情况，以及各维度的完成状态。",
        "export_zip": "导出 ZIP",
        "empty": "还没有分析记录，请先从项目页启动一次分析。",
        "progress": "整体进度",
        "concurrency": "实际并发",
        "slot_usage": "槽位占用",
        "current_facet": "当前维度",
        "queued_facets": "排队维度",
        "latest_event": "最新事件",
        "completed": "已完成",
        "failed": "失败",
        "llm_success": "LLM 成功",
        "llm_fallback": "LLM 回退",
        "input_tokens": "输入 Token",
        "output_tokens": "输出 Token",
        "total_tokens": "总 Token",
        "facet_queue": "维度队列",
        "event_stream": "事件流",
        "result_title": "分析结果",
        "rerun": "重跑维度",
        "no_events": "暂无事件",
        "no_evidence": "暂无证据",
        "no_conflicts": "暂无冲突记录",
        "live_output": "实时输出",
        "trace": "LLM 跟踪",
        "notes": "备注与冲突",
        "evidence": "证据",
        "queue_position": "排队位置",
        "last_updated": "最近更新时间",
        "waiting": "等待中",
        "open_assets": "前往资产",
    },
    "assets": {
        "title": "资产生成控制台",
        "eyebrow": "资产输出工作台",
        "hero_note": "在分析结果基础上生成 Skill 或画像报告，实时查看流式输出，并继续编辑草稿与版本。",
        "generator_title": "生成草稿",
        "generator_note": "优先使用流式生成，在完成后自动回到草稿编辑区。",
        "generate": "开始生成",
        "regenerate": "重新生成",
        "draft_title": "草稿编辑",
        "versions_title": "版本记录",
        "empty_draft": "当前还没有草稿，先完成分析再生成资产。",
        "empty_versions": "还没有已发布版本。",
        "stream_title": "实时输出",
        "status_idle": "待命",
        "status_running": "生成中",
        "status_completed": "已完成",
        "status_failed": "失败",
        "field_markdown": "Markdown",
        "field_json": "JSON Payload",
        "field_prompt": "Prompt 文本",
        "field_notes": "备注",
        "publish": "发布版本",
        "save_draft": "保存草稿",
        "view_playground": "进入试聊",
        "view_analysis": "返回分析",
        "stream_hint": "流式内容会同步写入下方草稿编辑区。",
        "fallback_hint": "如果流式生成失败，会自动回退到普通生成接口。",
    },
    "playground": {
        "title": "试聊验证",
        "eyebrow": "沉浸式对话验证",
        "hero_note_ready": "使用最新发布的 Skill 与角色进行试聊，观察口吻、立场与细节一致性。",
        "hero_note_missing": "还没有已发布 Skill，暂时无法进入试聊。",
        "empty_turns": "试聊环境已准备完成，发送第一条消息开始验证。",
        "send": "发送",
        "placeholder": "输入你想对角色说的话，按 Enter 发送，Shift + Enter 换行。",
        "publish_first": "请先在资产页发布一个 Skill 版本。",
        "system_notice": "系统提示",
        "you": "你",
        "version_label": "当前 Skill 版本",
    },
    "preprocess": {
        "title": "预分析工作区",
        "eyebrow": "预分析工作区",
        "hero_note": "通过 @文件名 引用语料，做预处理、检索、转换、抽样与临时产物生成。",
        "sessions": "会话",
        "new_session": "新建会话",
        "rename_session": "重命名",
        "delete_session": "删除会话",
        "documents": "文档",
        "artifacts": "生成文件",
        "composer_placeholder": "输入问题，或使用 @文件名 指定要处理的文档。按 Enter 发送，Shift + Enter 换行。",
        "composer_hint": "支持多文档上下文、检索、Python 转换和产物导出。",
        "untitled_session": "未命名会话",
        "artifact_empty": "当前会话还没有生成文件。",
        "document_empty": "当前项目还没有可引用文档。",
        "send": "发送",
        "sending": "发送中…",
        "working": "处理中…",
        "ready_context": "准备上下文",
        "rename_prompt": "输入新的会话标题",
        "execution_failed": "执行失败",
        "connection_interrupted": "连接已中断",
        "mention_insert": "插入",
        "mention_empty": "没有匹配的文档",
    },
    "settings": {
        "title": "设置",
        "eyebrow": "模型与服务配置",
        "hero_title": "配置 Chat LLM 与 Embedding 服务",
        "hero_note": "支持 OpenAI、xAI、Gemini 官方入口，以及兼容 OpenAI 的自定义服务。Chat LLM 额外支持 Responses API 与 Chat Completions API。",
        "chat_panel": "Chat LLM",
        "embedding_panel": "Embedding 模型",
        "provider": "Provider",
        "api_mode": "API 模式",
        "base_url": "Base URL",
        "api_key": "API Key",
        "model": "模型名称",
        "save_chat": "保存 Chat 配置",
        "save_embedding": "保存 Embedding 配置",
        "discover_models": "发现模型",
        "discover_loading": "正在拉取模型列表…",
        "discover_empty": "当前服务没有返回可用模型。",
        "discover_failed": "模型发现失败",
        "discover_result": "模型列表",
        "hint_openai": "留空时自动使用 OpenAI 官方入口 https://api.openai.com/v1",
        "hint_xai": "留空时自动使用 xAI 官方入口 https://api.x.ai/v1",
        "hint_gemini": "留空时自动使用 Gemini 官方 OpenAI 兼容入口",
        "hint_custom": "自定义 OpenAI Compatible 服务必须填写 Base URL。",
        "placeholder_openai": "留空时自动使用 OpenAI 官方入口",
        "placeholder_xai": "留空时自动使用 xAI 官方入口",
        "placeholder_gemini": "留空时自动使用 Gemini 官方兼容入口",
        "placeholder_custom": "例如 https://api.example.com/v1",
        "model_placeholder": "可手动填写，也可以点击“发现模型”自动探测",
    },
}


def page_strings(page_name: str) -> dict[str, Any]:
    page = deepcopy(PAGE_UI.get(page_name, {}))
    return {
        "locale": DEFAULT_LOCALE,
        "common": deepcopy(COMMON_UI),
        **page,
    }
