from __future__ import annotations

from copy import deepcopy
from typing import Any

DEFAULT_LOCALE = "zh-CN"

LOCALES: dict[str, dict[str, Any]] = {
    "zh-CN": {
        "common": {
            "app_name": "Persona Distiller",
            "brand_name": "角色蒸馏台",
            "brand_tagline": "本地语料控制台",
            "nav_projects": "项目",
            "nav_settings": "设置",
            "back_to_project": "返回项目",
            "back_to_analysis": "返回分析",
            "back_to_assets": "返回资产",
            "open_playground": "进入试聊",
            "open_preprocess": "进入预分析",
            "save": "保存",
            "cancel": "取消",
            "delete": "删除",
            "edit": "编辑",
            "close": "关闭",
            "details": "详情",
            "view": "查看",
            "retry": "重试",
            "refresh": "刷新",
            "loading": "加载中…",
            "request_failed": "请求失败",
            "unknown_error": "发生未知错误，请稍后再试。",
            "empty_state": "暂无内容",
            "created_at": "创建时间",
            "updated_at": "更新时间",
            "confirm_continue": "确认继续吗？",
            "confirm_delete_project": "确定删除这个项目及其相关数据吗？此操作不可恢复。",
            "confirm_delete_document": "确定删除这份文档吗？此操作不可恢复。",
            "confirm_delete_session": "确定删除这个会话吗？",
            "confirm_delete_profile": "确定删除这个画像吗？",
        },
        "page": {
            "index": {
                "title": "项目总览",
                "eyebrow": "项目总览控制台",
                "hero_title": "把语料、分析、资产和试聊放进同一个控制台",
                "hero_note": "保留 FastAPI + Jinja + 原生 JS 架构，在不引入新前端框架的前提下，统一管理上传、处理、分析、资产生成与试聊验证。",
                "launch_deck_label": "启动舱",
                "tech_stack_chip": "FastAPI + Jinja + 原生 JS",
                "workspaces_suffix": "个工作区",
                "metric_projects": "项目数量",
                "metric_note": "当前工作区内已创建的项目总数",
                "panel_create": "创建新项目",
                "panel_existing": "最近项目",
                "section_create_eyebrow": "创建",
                "new_workspace_chip": "新工作区",
                "section_systems_eyebrow": "系统",
                "workbench_chip": "控制台",
                "metric_chat_label": "Chat",
                "metric_embedding_label": "Embedding",
                "metric_interface_label": "界面",
                "metric_interface_value": "AGENT",
                "metric_interface_note": "赛博风工作台外壳",
                "metric_status_ready": "就绪",
                "metric_status_check": "检查",
                "section_workspace_eyebrow": "工作区",
                "create_name": "项目名称",
                "create_name_placeholder": "例如：Alice、创始人访谈、旅行群聊画像",
                "create_mode": "工作模式",
                "mode_group": "群组模式",
                "mode_group_hint": "适合群聊、社群、团队等多角色语料",
                "mode_single": "单人模式",
                "mode_single_hint": "适合单个人物、作者、主播或品牌人格",
                "mode_telegram": "Telegram 模式",
                "mode_telegram_hint": "适合 Telegram 导出的结构化群聊记录，分析直接基于 SQL 与 LLM Agent",
                "create_description": "项目说明",
                "create_description_placeholder": "说明语料来源、目标角色，以及需要重点保留的表达方式。",
                "create_submit": "创建项目",
                "empty_projects": "还没有项目，先创建一个开始搭建你的控制台。",
                "empty_projects_note": "创建第一个工作区，进入启动舱。",
                "status_chat_ready": "Chat LLM 已就绪",
                "status_chat_missing": "Chat LLM 未配置",
                "status_embedding_ready": "Embedding 已就绪",
                "status_embedding_missing": "Embedding 未配置，将回退到词法检索",
                "project_card_open": "打开项目",
                "project_card_edit": "编辑项目",
                "project_card_delete": "删除项目",
                "project_description_empty": "暂无项目说明",
                "project_updated": "最近更新",
                "modal_edit_title": "编辑项目",
                "modal_edit_eyebrow": "编辑",
                "modal_name": "项目名称",
                "modal_description": "项目说明",
                "modal_mode": "工作模式",
                "modal_submit": "保存修改",
            },
            "project": {
                "title": "项目控制台",
                "eyebrow": "项目控制中心",
                "task_bridge_label": "任务桥",
                "docs_suffix": "文档",
                "ready_suffix": "可分析",
                "back_to_parent": "返回父工作区",
                "open_assets": "资产",
                "section_upload_eyebrow": "上传",
                "upload_title": "语料上传与处理",
                "upload_hint": "拖拽或选择文件后可直接批量处理，文档状态和任务进度会自动刷新。",
                "dropzone_title": "拖拽文件到这里，或点击选择文档",
                "dropzone_note": "支持 html、json、jsonl、docx、pdf、txt、md、log",
                "analysis_title": "分析配置",
                "analysis_eyebrow": "分析",
                "analysis_target_role": "目标角色",
                "analysis_context": "分析上下文",
                "analysis_concurrency": "分析并发",
                "analysis_submit_disabled": "需要先处理可分析文档",
                "analysis_submit": "启动分析",
                "analysis_help": "这些配置会进入检索、分析和资产合成流程。",
                "analysis_group_note": "群组模式请先创建画像，再按画像分别启动分析。",
                "group_profiles": "群组画像",
                "group_profiles_empty": "还没有群组成员画像，先添加一个角色。",
                "add_profile": "添加画像",
                "profiles_eyebrow": "画像",
                "open_persona": "打开画像",
                "profile_name": "角色名称",
                "profile_description": "角色说明",
                "profile_submit": "保存画像",
                "profile_delete_confirm": "确定删除这个画像吗？",
                "profile_view_analysis": "查看分析",
                "profile_view_asset": "查看资产",
                "profile_run_analysis": "生成分析",
                "document_panel": "文档处理看板",
                "document_empty": "当前项目还没有文档。",
                "document_load_more": "加载更多",
                "document_filter_all": "全部",
                "document_filter_ready": "可分析",
                "document_filter_active": "处理中",
                "document_filter_failed": "失败",
                "refresh_documents": "刷新列表",
                "process_all": "一键处理",
                "retry_all": "失败重试",
                "stop_processing": "停止处理",
                "stats_total": "文档总数",
                "stats_ready": "可分析",
                "stats_pending": "待处理",
                "stats_failed": "失败",
                "section_status_eyebrow": "状态",
                "workspace_telemetry_title": "工作区遥测",
                "modal_document_title": "文档详情",
                "modal_document_eyebrow": "文档",
                "modal_process_document": "处理此文档",
                "modal_retry_document": "重新处理",
                "modal_save_document": "保存文档信息",
                "modal_edit_project": "编辑项目",
                "modal_edit_eyebrow": "编辑",
                "modal_project_name_label": "项目名称",
                "modal_project_description_label": "项目说明",
                "modal_add_profile": "添加群组画像",
                "modal_profile_eyebrow": "画像",
                "workspace_mode": "工作模式",
                "single_mode": "单人模式",
                "group_mode": "群组模式",
                "telegram_mode": "Telegram 模式",
                "no_project_description": "这个项目还没有说明，你可以补充语料背景和目标角色。",
                "latest_analysis": "最新分析",
                "not_analyzed": "尚未分析",
                "latest_release": "最新发布",
                "unreleased": "尚未发布",
                "queued": "已排队",
                "processing": "处理中",
                "ready": "可分析",
                "failed": "失败",
                "unprocessed": "未处理",
                "upload_success": "文档上传完成。",
                "upload_empty": "请先选择至少一个文件。",
                "uploading": "正在上传文档…",
                "process_success": "任务已加入处理队列。",
                "retry_success": "失败文档已重新加入处理队列。",
                "stop_success": "当前项目的处理任务已停止。",
                "document_save_success": "文档信息已保存。",
                "document_delete_success": "文档已删除。",
                "document_filename": "文件名",
                "document_status": "状态",
                "document_source_type": "来源类型",
                "document_language": "语言",
                "document_note": "备注",
                "document_error": "错误信息",
                "document_task_stage": "任务阶段",
                "document_progress": "处理进度",
                "document_open": "查看详情",
                "document_delete": "删除文档",
                "document_queued_hint": "处理中队列会自动推送最新状态。",
                "child_project_hint": "子画像项目沿用父项目文档，请返回群组项目管理语料。",
                "child_project_dataset_note": "这个 Telegram 子画像复用父工作区的数据集。请回到父工作区完成上传与预分析。",
                "profile_description_empty": "暂无画像说明",
                "analysis_telegram_note": "Telegram 模式会先生成分阶段对话报告，再由 LLM 结合数据库工具回查证据，不使用 embedding 检索。",
                "section_documents_eyebrow": "文档",
                "latest_run_eyebrow": "最近运行",
                "latest_run_status_label": "状态",
                "latest_run_id_label": "Run",
                "telegram_stats_top_users": "Top Users",
                "telegram_stats_current_bind": "当前绑定",
                "telegram_stats_pending": "待绑定",
                "telegram_persona_eyebrow": "画像工作台",
                "telegram_persona_title": "Telegram 画像工作台",
                "telegram_persona_stage_chip": "创建 → 绑定 → 分析",
                "telegram_persona_step01_title": "选择目标用户",
                "telegram_persona_step01_note": "优先使用最新预分析产出的 Top Users；只有在 Top 列表之外才使用手动搜索。",
                "telegram_persona_top_prefix": "TOP",
                "telegram_persona_messages_suffix": "条消息",
                "telegram_persona_manual_fallback_label": "手动目标兜底",
                "telegram_persona_target_query_placeholder": "显示名 / 用户名 / UID",
                "telegram_persona_step02_title": "补全画像上下文",
                "telegram_persona_step02_note": "画像名称会自动跟随选中目标别名；分析上下文默认继承父项目说明。",
                "telegram_persona_persona_name_label": "画像名称",
                "telegram_persona_persona_name_placeholder": "例如：Bob Persona",
                "telegram_persona_step03_title": "创建并启动分析",
                "telegram_persona_step03_note": "提交后会创建并绑定 Telegram 子画像，立即启动首轮分析并跳转到分析中心。",
                "telegram_persona_step03_policy_note": "Telegram 父工作区只保留一条推荐路径：选人 → 创建子画像 → 立即分析。",
                "telegram_persona_submit_create_and_analyze": "创建画像并分析",
                "telegram_persona_waiting_chip": "等待中",
                "telegram_persona_select_user_first": "先选择一个 Telegram 用户",
                "telegram_persona_target_summary_note": "选中的用户会成为子画像绑定目标，后续重跑会复用该目标。",
                "telegram_persona_run_policy_title": "运行策略",
                "telegram_persona_policy_top_users": "Top Users",
                "telegram_persona_policy_auto_analyze": "自动分析",
                "telegram_persona_policy_enabled": "已启用",
                "telegram_persona_policy_binding_source": "绑定来源",
                "telegram_persona_policy_latest_preprocess": "最新预分析",
                "telegram_persona_waiting_preprocess_title": "Telegram 画像工作台正在等待预分析结果。",
                "telegram_persona_waiting_preprocess_note": "请先完成一次成功的 Telegram 预分析，以便生成 Top Users 列表并启用创建-绑定流程。",
                "telegram_child_eyebrow": "子画像",
                "telegram_child_title": "Telegram 子画像",
                "telegram_child_rebind_from_parent": "回到父工作区重新绑定",
                "telegram_child_bound_target_chip": "已绑定目标",
                "telegram_child_recovered_hint": "从最近一次成功运行摘要中恢复。",
                "telegram_child_rerun_only_note": "此子画像已绑定 Telegram 用户；后续重跑仅更新上下文与分析参数。",
                "telegram_child_submit_rerun": "重跑画像分析",
                "telegram_child_submit_start": "启动画像分析",
                "telegram_child_open_latest_analysis": "打开最新分析",
                "telegram_child_snapshot_title": "快照",
                "telegram_child_snapshot_bound_user": "绑定用户",
                "telegram_child_snapshot_latest_run": "最近运行",
                "telegram_child_snapshot_not_started": "尚未开始",
                "telegram_child_snapshot_rebind_path": "重新绑定路径",
                "telegram_child_snapshot_parent_workspace": "父工作区",
                "telegram_child_needs_binding_title": "这个 Telegram 子画像还没有绑定目标。",
                "telegram_child_needs_binding_note": "旧版子画像需要先完成一次绑定运行，之后界面会自动进入仅重跑模式。",
                "telegram_child_bind_step01_title": "绑定目标用户",
                "telegram_child_bind_step01_note": "这次运行完成后，子画像会记住当前目标，后续只需要重跑即可。",
                "telegram_child_bind_step02_title": "分析上下文",
                "telegram_child_bind_step02_note": "先完成一次绑定分析；之后的重跑不再显示 Top User 选择器。",
                "telegram_child_bind_submit_bind_and_start": "绑定并启动分析",
                "telegram_child_bind_pending_bind_chip": "等待绑定",
                "telegram_child_bind_pending_bind_note": "首次成功运行会成为子画像的绑定快照。",
                "telegram_child_bind_preprocess_first_note": "请先在父工作区运行 Telegram 预分析，然后回到这里绑定目标用户。",
                "telegram_personas_section_eyebrow": "画像",
                "telegram_personas_created_title": "已创建画像",
                "telegram_personas_pending_bind_chip": "待绑定",
                "telegram_personas_bound_user_chip": "已绑定用户",
                "telegram_personas_recovered_hint": "从最近一次运行摘要中恢复。",
                "telegram_personas_needs_binding_chip": "需要绑定",
                "telegram_personas_needs_binding_title": "这个画像还没有 Telegram 目标。",
                "telegram_personas_needs_binding_note": "打开一次子画像完成首轮绑定分析后，后续即可直接重跑。",
                "telegram_personas_rerun": "重跑",
                "telegram_personas_continue_binding": "继续绑定",
                "telegram_personas_open": "打开",
                "telegram_personas_empty_title": "还没有 Telegram 子画像。",
                "telegram_personas_empty_note": "在 Persona Studio 中选择目标用户即可创建第一个绑定画像。",
                "telegram_picker_selected_chip": "已选择目标",
                "telegram_picker_manual_chip": "手动搜索",
                "telegram_picker_select_first_title": "先选择一个 Telegram 用户",
                "telegram_picker_selected_note": "将用这个目标直接创建并绑定子画像。",
                "telegram_picker_manual_note": "将使用当前搜索词去解析目标用户。",
                "telegram_picker_pending_chip": "待选择",
                "telegram_picker_pending_note": "创建后会直接进入绑定好的分析流程，不再重复选择 Top User。",
                "ingest_stage_queued": "排队中",
                "ingest_stage_parsing": "解析中",
                "ingest_stage_chunking": "切块中",
                "ingest_stage_embedding": "生成向量",
                "ingest_stage_storing": "写入索引",
                "ingest_stage_completed": "已完成",
                "ingest_stage_failed": "失败",
            },
            "analysis": {
                "title": "分析监控",
                "eyebrow": "分析运行监控",
                "hero_note": "实时查看队列、槽位占用、最新事件、LLM 成功与回退情况，以及各维度的完成状态。",
                "banner_title_label": "智能分析中心",
                "banner_lanes_label": "多 Agent 轨道",
                "banner_diagnostics_label": "维度诊断",
                "agent_center_eyebrow": "Agent 中枢",
                "agent_center_title": "智能分析中心",
                "live_connecting": "连接中",
                "run_pulse_eyebrow": "运行脉冲",
                "run_state_eyebrow": "运行状态",
                "active_agents_label": "活跃 Agents",
                "requested_label": "请求并发",
                "effective_label": "实际并发",
                "live_agents_label": "在线 Agents",
                "export_zip": "导出 ZIP",
                "empty": "还没有分析记录，请先从项目页启动一次分析。",
                "progress": "整体进度",
                "concurrency": "实际并发",
                "slot_usage": "槽位占用",
                "current_facet": "当前维度",
                "queued_facets": "排队维度",
                "latest_event": "最新事件",
                "completed": "已完成",
                "running": "运行中",
                "queued": "排队中",
                "failed": "失败",
                "llm_success": "LLM 成功",
                "llm_fallback": "LLM 回退",
                "input_tokens": "输入 Token",
                "output_tokens": "输出 Token",
                "total_tokens": "总 Token",
                "facet_queue": "维度队列",
                "event_stream": "事件流",
                "result_title": "分析结果",
                "rerun": "重跑维度",
                "no_events": "暂无事件",
                "no_evidence": "暂无证据",
                "no_conflicts": "暂无冲突记录",
                "live_output": "实时输出",
                "trace": "LLM 跟踪",
                "notes": "备注与冲突",
                "evidence": "证据",
                "queue_position": "排队位置",
                "last_updated": "最近更新时间",
                "waiting": "等待中",
                "no_active_agents": "暂无活跃 Agent。",
                "inspect_event_stream_summary": "查看原始事件流与实时诊断",
                "open_assets": "前往资产",
            },
            "assets": {
                "title": "资产生成控制台",
                "eyebrow": "资产输出工作台",
                "hero_note": "在分析结果基础上生成 Skill 或画像报告，实时查看流式输出，并继续编辑草稿与版本。",
                "generator_title": "生成草稿",
                "generator_note": "优先使用流式生成，在完成后自动回到草稿编辑区。",
                "generate": "开始生成",
                "regenerate": "重新生成",
                "draft_title": "草稿编辑",
                "versions_title": "版本记录",
                "empty_draft": "当前还没有草稿，先完成分析再生成资产。",
                "empty_versions": "还没有已发布版本。",
                "stream_title": "实时输出",
                "status_idle": "待命",
                "status_running": "生成中",
                "status_completed": "已完成",
                "status_failed": "失败",
                "field_markdown": "Markdown",
                "field_json": "JSON Payload",
                "field_prompt": "Prompt 文本",
                "field_notes": "备注",
                "prompt_locked_hint": "Skill 的实际对话 Prompt 现在跟随 Skill_merge.md，同步使用上方 Markdown。",
                "publish": "发布版本",
                "save_draft": "保存草稿",
                "view_playground": "进入试聊",
                "view_analysis": "返回分析",
                "stream_hint": "流式内容会同步写入下方草稿编辑区。",
                "fallback_hint": "如果流式生成失败，会自动回退到普通生成接口。",
                "draft_exports_title": "草稿导出",
                "version_exports_title": "版本导出",
                "export_bundle": "导出 ZIP",
                "export_skill_doc": "Skill.md",
                "export_personality_doc": "personality.md",
                "export_memories_doc": "memories.md",
                "export_merge_doc": "Skill_merge.md",
            },
            "playground": {
                "title": "试聊验证",
                "eyebrow": "沉浸式对话验证",
                "hero_note_ready": "使用最新发布的 Skill 与角色进行试聊，观察口吻、立场与细节一致性。",
                "hero_note_missing": "还没有已发布 Skill，暂时无法进入试聊。",
                "empty_turns": "试聊环境已准备完成，发送第一条消息开始验证。",
                "send": "发送",
                "placeholder": "输入你想对角色说的话，按 Enter 发送，Shift + Enter 换行。",
                "publish_first": "请先在资产页发布一个 Skill 版本。",
                "system_notice": "系统提示",
                "you": "你",
                "version_label": "当前 Skill 版本",
            },
            "preprocess": {
                "title": "预分析工作区",
                "eyebrow": "预分析工作区",
                "hero_note": "通过 @文件名 引用语料，做预处理、检索、转换、抽样与临时产物生成。",
                "sessions": "会话",
                "new_session": "新建会话",
                "rename_session": "重命名",
                "delete_session": "删除会话",
                "documents": "文档",
                "artifacts": "生成文件",
                "composer_placeholder": "输入问题，或使用 @文件名 指定要处理的文档。按 Enter 发送，Shift + Enter 换行。",
                "composer_hint": "支持多文档上下文、检索、Python 转换和产物导出。",
                "untitled_session": "未命名会话",
                "artifact_empty": "当前会话还没有生成文件。",
                "document_empty": "当前项目还没有可引用文档。",
                "send": "发送",
                "sending": "发送中…",
                "working": "处理中…",
                "ready_context": "准备上下文",
                "rename_prompt": "输入新的会话标题",
                "execution_failed": "执行失败",
                "connection_interrupted": "连接已中断",
                "mention_insert": "插入",
                "mention_empty": "没有匹配的文档",
            },
            "settings": {
                "title": "设置",
                "eyebrow": "模型与服务配置",
                "hero_title": "配置 Chat LLM 与 Embedding 服务",
                "hero_note": "支持 OpenAI、xAI、Gemini 官方入口，以及兼容 OpenAI 的自定义服务。Chat LLM 额外支持 Responses API 与 Chat Completions API。",
                "chat_panel": "Chat LLM",
                "embedding_panel": "Embedding 模型",
                "provider": "Provider",
                "api_mode": "API 模式",
                "base_url": "Base URL",
                "api_key": "API Key",
                "model": "模型名称",
                "save_chat": "保存 Chat 配置",
                "save_embedding": "保存 Embedding 配置",
                "discover_models": "发现模型",
                "discover_loading": "正在拉取模型列表…",
                "discover_empty": "当前服务没有返回可用模型。",
                "discover_failed": "模型发现失败",
                "discover_result": "模型列表",
                "hint_openai": "留空时自动使用 OpenAI 官方入口 https://api.openai.com/v1",
                "hint_xai": "留空时自动使用 xAI 官方入口 https://api.x.ai/v1",
                "hint_gemini": "留空时自动使用 Gemini 官方 OpenAI 兼容入口",
                "hint_custom": "自定义 OpenAI Compatible 服务必须填写 Base URL。",
                "placeholder_openai": "留空时自动使用 OpenAI 官方入口",
                "placeholder_xai": "留空时自动使用 xAI 官方入口",
                "placeholder_gemini": "留空时自动使用 Gemini 官方兼容入口",
                "placeholder_custom": "例如 https://api.example.com/v1",
                "model_placeholder": "可手动填写，也可以点击“发现模型”自动探测",
                "hero_label": "Config Matrix",
                "hero_chip_chat": "Chat Orchestration",
                "hero_chip_embedding": "Embedding Routing",
                "hero_chip_active": "Active 优先",
                "hero_chip_fallback": "Fallback 有序",
                "hero_stat_configs": "配置槽位",
                "hero_stat_providers": "Provider 类型",
                "hero_stat_services": "服务通道",
                "service_chat_eyebrow": "Chat Orchestration",
                "service_embedding_eyebrow": "Embedding Routing",
                "service_chat_summary": "把多个 Chat 入口组织成主备链路，快速切换 Provider 与 API 模式。",
                "service_embedding_summary": "为 Embedding 服务维护主备链路，确保检索与召回持续可用。",
                "config_unit": "项",
                "save_order": "保存排序与切换",
                "add_config": "添加配置",
                "sequence_title": "配置分页",
                "page_sequence_note": "点击分页卡片切换配置，当前顺序就是回退顺序。",
                "selected_config": "当前编辑",
                "previous": "上一页",
                "next": "下一页",
                "config_count": "配置数量",
                "active_config": "当前 Active",
                "fallback_count": "回退数量",
                "provider_coverage": "Provider 覆盖",
                "move_up": "上移",
                "move_down": "下移",
                "delete_config": "删除配置",
                "config_name": "配置名称",
                "fallback_note": "回退说明",
                "fallback_active": "当前主配置",
                "fallback_ordered": "按当前排序参与回退",
                "model_select": "模型下拉",
                "model_override": "手动模型覆盖",
                "save_and_sync": "保存并同步模型",
                "save_sync_hint": "保存后会立即拉取模型列表，并刷新该配置的候选模型。",
                "models_discovered": "已发现模型",
                "order_position": "排序位置",
                "active_status": "ACTIVE",
                "fallback_status": "FALLBACK",
                "model_select_placeholder": "保存后自动查询模型列表",
                "notice_added": "已新增空配置，填写后保存即可。",
                "notice_switched": "已切换活跃配置，记得保存需要同步模型的配置。",
                "notice_reordered": "已调整配置顺序。",
                "notice_removed": "已移除配置。",
                "notice_saving": "正在保存设置...",
                "notice_syncing": "正在保存并同步模型...",
                "notice_saved": "已保存当前顺序与活跃配置。",
                "notice_synced": "已保存并同步模型列表。",
                "notice_sync_failed_prefix": "已保存，但模型同步失败：",
                "notice_save_failed": "保存失败。",
            },
            "telegram_preprocess": {
                "title": "Telegram 预处理",
                "hero_title": "Telegram 预处理指挥台",
                "hero_note": "导入结构化 JSON 后，这里会实时显示 SQL 物化、周总结并发、话题沉淀与中间产物状态。",
                "concurrency_label": "周总结并发",
                "btn_resume": "继续预处理",
                "btn_start": "开始预处理",
                "stage_waiting": "等待开始",
                "live_note": "实时监听 SQL 物化、周总结和最终话题写入的进度。",
                "status_waiting": "等待任务",
                "overall_progress": "总体进度",
                "coverage_progress": "周总结覆盖率",
                "current_run": "当前 Run",
                "stage": "阶段",
                "total_progress": "总进度",
                "weekly_candidates": "周候选数",
                "final_topics": "最终话题数",
                "request_concurrency": "请求并发",
                "active_workers": "活跃 Worker",
                "completed_weeks": "已完成周数",
                "remaining_weeks": "剩余周数",
                "no_run": "暂无预处理 run",
                "worker_lanes": "并发轨道",
                "no_workers": "尚无活跃 worker。",
                "trace_timeline": "Subagent 时间线",
                "waiting_events": "等待任务事件。",
                "live_output": "当前 LLM 输出",
                "waiting_llm": "等待新的 LLM 请求开始。",
                "empty_weekly": "当前 Run 还没有周候选结果。",
                "empty_top": "当前 Run 还没有 Top Users 结果。",
                "empty_active": "当前 Run 还没有活跃用户结果。",
                "topic_table": "周话题表",
                "empty_topics": "当前 Run 还没有最终话题结果。",
                "history_run": "历史 Run",
                "empty_history": "暂无历史预处理记录。"
            },
            "skill": {
                "preview": "Skill 预览",
                "draft_title": "的 Skill 草稿",
                "hero_note": "从最新分析生成草稿，编辑后再发布为正式版本。",
                "regenerate": "重新生成草稿",
                "back_to_analysis": "返回分析",
                "draft_eyebrow": "草稿",
                "edit_draft": "编辑草稿",
                "review_notes": "审核备注",
                "save_draft": "保存草稿",
                "publish_version": "发布版本",
                "no_draft": "当前没有草稿。先等分析完成，再生成 Skill。",
                "version_history": "版本记录",
                "published_versions": "已发布版本",
                "published": "已发布",
                "no_versions": "暂无已发布版本。"
            }
        }
    },
    "en-US": {
        "common": {
            "app_name": "Persona Distiller",
            "brand_name": "Persona Distiller",
            "brand_tagline": "Local Corpus Console",
            "nav_projects": "Projects",
            "nav_settings": "Settings",
            "back_to_project": "Back to Project",
            "back_to_analysis": "Back to Analysis",
            "back_to_assets": "Back to Assets",
            "open_playground": "Open Playground",
            "open_preprocess": "Open Preprocess",
            "save": "Save",
            "cancel": "Cancel",
            "delete": "Delete",
            "edit": "Edit",
            "close": "Close",
            "details": "Details",
            "view": "View",
            "retry": "Retry",
            "refresh": "Refresh",
            "loading": "Loading...",
            "request_failed": "Request Failed",
            "unknown_error": "An unknown error occurred, please try again later.",
            "empty_state": "No Content",
            "created_at": "Created At",
            "updated_at": "Updated At",
            "confirm_continue": "Are you sure to continue?",
            "confirm_delete_project": "Are you sure you want to delete this project and its data? This action is irreversible.",
            "confirm_delete_document": "Are you sure you want to delete this document? This action is irreversible.",
            "confirm_delete_session": "Are you sure you want to delete this session?",
            "confirm_delete_profile": "Are you sure you want to delete this profile?",
        },
        "page": {
            "index": {
                "title": "Projects Overview",
                "eyebrow": "Projects Overview Console",
                "hero_title": "Manage corpus, analysis, assets, and playground in one place",
                "hero_note": "Preserves FastAPI + Jinja + vanilla JS architecture without introducing new frontend frameworks, unifying the workflow from upload to analysis and testing.",
                "launch_deck_label": "Launch Deck",
                "tech_stack_chip": "FastAPI + Jinja + Native JS",
                "workspaces_suffix": "workspaces",
                "metric_projects": "Total Projects",
                "metric_note": "Number of projects created in the current workspace",
                "panel_create": "Create New Project",
                "panel_existing": "Recent Projects",
                "section_create_eyebrow": "Create",
                "new_workspace_chip": "New workspace",
                "section_systems_eyebrow": "Systems",
                "workbench_chip": "Workbench",
                "metric_chat_label": "Chat",
                "metric_embedding_label": "Embedding",
                "metric_interface_label": "Interface",
                "metric_interface_value": "AGENT",
                "metric_interface_note": "Cyber-aesthetic workstation shell",
                "metric_status_ready": "READY",
                "metric_status_check": "CHECK",
                "section_workspace_eyebrow": "Workspace",
                "create_name": "Project Name",
                "create_name_placeholder": "e.g., Alice, Founder Interviews, Travel Group Persona",
                "create_mode": "Workspace Mode",
                "mode_group": "Group Mode",
                "mode_group_hint": "Suitable for group chats, communities, and multi-character corpus",
                "mode_single": "Single Mode",
                "mode_single_hint": "Suitable for a single person, author, streamer, or brand persona",
                "mode_telegram": "Telegram Mode",
                "mode_telegram_hint": "Suitable for structured Telegram chat exports, directly based on SQL and LLM Agent analysis",
                "create_description": "Project Description",
                "create_description_placeholder": "Explain the corpus source, target persona, and key expressions to retain.",
                "create_submit": "Create Project",
                "empty_projects": "No projects yet. Create one to start building your console.",
                "empty_projects_note": "Create the first workspace to open the launch deck.",
                "status_chat_ready": "Chat LLM Ready",
                "status_chat_missing": "Chat LLM Not Configured",
                "status_embedding_ready": "Embedding Ready",
                "status_embedding_missing": "Embedding Not Configured, falling back to lexical search",
                "project_card_open": "Open Project",
                "project_card_edit": "Edit Project",
                "project_card_delete": "Delete Project",
                "project_description_empty": "No project description",
                "project_updated": "Last Updated",
                "modal_edit_title": "Edit Project",
                "modal_edit_eyebrow": "Edit",
                "modal_name": "Project Name",
                "modal_description": "Project Description",
                "modal_mode": "Workspace Mode",
                "modal_submit": "Save Changes",
            },
            "project": {
                "title": "Project Console",
                "eyebrow": "Project Control Center",
                "task_bridge_label": "Task Bridge",
                "docs_suffix": "docs",
                "ready_suffix": "ready",
                "back_to_parent": "Back to parent",
                "open_assets": "Assets",
                "section_upload_eyebrow": "Upload",
                "upload_title": "Corpus Upload & Process",
                "upload_hint": "Drag & drop or select files to process in batch. Document status and task progress will refresh automatically.",
                "dropzone_title": "Drag files here, or click to select",
                "dropzone_note": "Supports html, json, jsonl, docx, pdf, txt, md, log",
                "analysis_title": "Analysis Config",
                "analysis_eyebrow": "Analysis",
                "analysis_target_role": "Target Persona",
                "analysis_context": "Analysis Context",
                "analysis_concurrency": "Concurrency",
                "analysis_submit_disabled": "Process documents first",
                "analysis_submit": "Start Analysis",
                "analysis_help": "These configurations will be used in the retrieval, analysis, and asset generation flow.",
                "analysis_group_note": "For group mode, please create profiles first, then start analysis per profile.",
                "group_profiles": "Group Profiles",
                "group_profiles_empty": "No group member profiles yet, add a persona first.",
                "add_profile": "Add Profile",
                "profiles_eyebrow": "Profiles",
                "open_persona": "Open persona",
                "profile_name": "Persona Name",
                "profile_description": "Persona Description",
                "profile_submit": "Save Profile",
                "profile_delete_confirm": "Are you sure you want to delete this profile?",
                "profile_view_analysis": "View Analysis",
                "profile_view_asset": "View Assets",
                "profile_run_analysis": "Run Analysis",
                "document_panel": "Document Processing Board",
                "document_empty": "No documents in this project yet.",
                "document_load_more": "Load More",
                "document_filter_all": "All",
                "document_filter_ready": "Ready",
                "document_filter_active": "Processing",
                "document_filter_failed": "Failed",
                "refresh_documents": "Refresh List",
                "process_all": "Process All",
                "retry_all": "Retry Failed",
                "stop_processing": "Stop Processing",
                "stats_total": "Total",
                "stats_ready": "Ready",
                "stats_pending": "Pending",
                "stats_failed": "Failed",
                "section_status_eyebrow": "Status",
                "workspace_telemetry_title": "Workspace telemetry",
                "modal_document_title": "Document Details",
                "modal_document_eyebrow": "Document",
                "modal_process_document": "Process Document",
                "modal_retry_document": "Retry Processing",
                "modal_save_document": "Save Document Info",
                "modal_edit_project": "Edit Project",
                "modal_edit_eyebrow": "Edit",
                "modal_project_name_label": "Project name",
                "modal_project_description_label": "Project description",
                "modal_add_profile": "Add Group Profile",
                "modal_profile_eyebrow": "Profile",
                "workspace_mode": "Workspace Mode",
                "single_mode": "Single Mode",
                "group_mode": "Group Mode",
                "telegram_mode": "Telegram Mode",
                "no_project_description": "This project has no description yet. You can add context and target persona details.",
                "latest_analysis": "Latest Analysis",
                "not_analyzed": "Not Analyzed",
                "latest_release": "Latest Release",
                "unreleased": "Unreleased",
                "queued": "Queued",
                "processing": "Processing",
                "ready": "Ready",
                "failed": "Failed",
                "unprocessed": "Unprocessed",
                "upload_success": "Document upload completed.",
                "upload_empty": "Please select at least one file.",
                "uploading": "Uploading documents...",
                "process_success": "Tasks added to the processing queue.",
                "retry_success": "Failed documents re-added to the processing queue.",
                "stop_success": "Processing tasks for the current project have been stopped.",
                "document_save_success": "Document info saved.",
                "document_delete_success": "Document deleted.",
                "document_filename": "Filename",
                "document_status": "Status",
                "document_source_type": "Source Type",
                "document_language": "Language",
                "document_note": "Note",
                "document_error": "Error Message",
                "document_task_stage": "Task Stage",
                "document_progress": "Progress",
                "document_open": "View Details",
                "document_delete": "Delete Document",
                "document_queued_hint": "The processing queue will push updates automatically.",
                "child_project_hint": "Child profile projects inherit documents from the parent project. Return to the group project to manage corpus.",
                "child_project_dataset_note": "This Telegram child persona reuses the parent workspace dataset. Return to the parent workspace for uploads and preprocess actions.",
                "profile_description_empty": "No profile description",
                "analysis_telegram_note": "Telegram mode will first generate phased chat reports, then use LLM with database tools to query evidence, without embedding retrieval.",
                "section_documents_eyebrow": "Documents",
                "latest_run_eyebrow": "Latest Run",
                "latest_run_status_label": "Status",
                "latest_run_id_label": "Run",
                "telegram_stats_top_users": "Top Users",
                "telegram_stats_current_bind": "Current bind",
                "telegram_stats_pending": "Pending",
                "telegram_persona_eyebrow": "Persona Studio",
                "telegram_persona_title": "Telegram Persona Studio",
                "telegram_persona_stage_chip": "Create → Bind → Analyze",
                "telegram_persona_step01_title": "Select target user",
                "telegram_persona_step01_note": "Use the latest preprocess top users first. Manual search is only a fallback for users outside the top list.",
                "telegram_persona_top_prefix": "Top",
                "telegram_persona_messages_suffix": "messages",
                "telegram_persona_manual_fallback_label": "Manual target fallback",
                "telegram_persona_target_query_placeholder": "Display name / username / UID",
                "telegram_persona_step02_title": "Fill persona context",
                "telegram_persona_step02_note": "The persona name auto-follows the selected alias, while analysis context inherits the parent project description.",
                "telegram_persona_persona_name_label": "Persona name",
                "telegram_persona_persona_name_placeholder": "Bob Persona",
                "telegram_persona_step03_title": "Create and start analysis",
                "telegram_persona_step03_note": "Submitting creates a bound Telegram child persona, immediately starts the first run, and jumps to the analysis center.",
                "telegram_persona_step03_policy_note": "Telegram parent workspaces now have a single recommended path. No more empty child persona followed by a second target selection.",
                "telegram_persona_submit_create_and_analyze": "Create persona and analyze",
                "telegram_persona_waiting_chip": "Waiting",
                "telegram_persona_select_user_first": "Select a Telegram user first",
                "telegram_persona_target_summary_note": "The selected user becomes the bound target for the child persona and is reused on reruns.",
                "telegram_persona_run_policy_title": "Run Policy",
                "telegram_persona_policy_top_users": "Top users",
                "telegram_persona_policy_auto_analyze": "Auto analyze",
                "telegram_persona_policy_enabled": "Enabled",
                "telegram_persona_policy_binding_source": "Binding source",
                "telegram_persona_policy_latest_preprocess": "Latest preprocess",
                "telegram_persona_waiting_preprocess_title": "Telegram Persona Studio is waiting for preprocess output.",
                "telegram_persona_waiting_preprocess_note": "Run a successful Telegram preprocess first so the top user list can seed the create-and-bind workflow.",
                "telegram_child_eyebrow": "Persona",
                "telegram_child_title": "Telegram child persona",
                "telegram_child_rebind_from_parent": "Rebind from parent",
                "telegram_child_bound_target_chip": "Bound target",
                "telegram_child_recovered_hint": "Recovered from the latest successful run summary.",
                "telegram_child_rerun_only_note": "This child persona is already bound to a Telegram user. Reruns only update context and analysis parameters.",
                "telegram_child_submit_rerun": "Rerun persona analysis",
                "telegram_child_submit_start": "Start persona analysis",
                "telegram_child_open_latest_analysis": "Open latest analysis",
                "telegram_child_snapshot_title": "Snapshot",
                "telegram_child_snapshot_bound_user": "Bound user",
                "telegram_child_snapshot_latest_run": "Latest run",
                "telegram_child_snapshot_not_started": "Not started",
                "telegram_child_snapshot_rebind_path": "Rebind path",
                "telegram_child_snapshot_parent_workspace": "Parent workspace",
                "telegram_child_needs_binding_title": "This Telegram child persona still needs a bound target.",
                "telegram_child_needs_binding_note": "Legacy child personas bind once, then automatically switch into rerun mode.",
                "telegram_child_bind_step01_title": "Bind target user",
                "telegram_child_bind_step01_note": "Once this run completes, the child persona remembers the current target and the UI becomes rerun-only.",
                "telegram_child_bind_step02_title": "Analysis context",
                "telegram_child_bind_step02_note": "Complete this first bound analysis once. Future runs no longer ask for a visible top user selector.",
                "telegram_child_bind_submit_bind_and_start": "Bind and start analysis",
                "telegram_child_bind_pending_bind_chip": "Pending bind",
                "telegram_child_bind_pending_bind_note": "This first successful run becomes the bound target snapshot for the child persona.",
                "telegram_child_bind_preprocess_first_note": "Run Telegram preprocess on the parent workspace first, then return here to bind a target user.",
                "telegram_personas_section_eyebrow": "Personas",
                "telegram_personas_created_title": "Created personas",
                "telegram_personas_pending_bind_chip": "Pending bind",
                "telegram_personas_bound_user_chip": "Bound user",
                "telegram_personas_recovered_hint": "Recovered from latest run summary.",
                "telegram_personas_needs_binding_chip": "Needs binding",
                "telegram_personas_needs_binding_title": "This persona has no Telegram target yet.",
                "telegram_personas_needs_binding_note": "Open the child persona once to finish its first bound analysis run.",
                "telegram_personas_rerun": "Rerun",
                "telegram_personas_continue_binding": "Continue binding",
                "telegram_personas_open": "Open",
                "telegram_personas_empty_title": "No Telegram child personas yet.",
                "telegram_personas_empty_note": "Select a target user in Persona Studio to create the first bound persona.",
                "telegram_picker_selected_chip": "Selected target",
                "telegram_picker_manual_chip": "Manual search",
                "telegram_picker_select_first_title": "Select a Telegram user first",
                "telegram_picker_selected_note": "This target will be used to create and bind a child persona.",
                "telegram_picker_manual_note": "This query will be used to resolve the target user.",
                "telegram_picker_pending_chip": "Pending",
                "telegram_picker_pending_note": "After creation, you'll jump into the bound analysis flow without re-selecting a top user.",
                "ingest_stage_queued": "Queued",
                "ingest_stage_parsing": "Parsing",
                "ingest_stage_chunking": "Chunking",
                "ingest_stage_embedding": "Embedding",
                "ingest_stage_storing": "Storing",
                "ingest_stage_completed": "Completed",
                "ingest_stage_failed": "Failed",
            },
            "analysis": {
                "title": "Analysis Monitor",
                "eyebrow": "Analysis Execution Monitor",
                "hero_note": "Monitor queue, slot usage, latest events, LLM success and fallback rates, and facet completion status in real time.",
                "banner_title_label": "Agentic Analysis Center",
                "banner_lanes_label": "Multi-agent lanes",
                "banner_diagnostics_label": "Facet diagnostics",
                "agent_center_eyebrow": "Agent Center",
                "agent_center_title": "Agentic Analysis Center",
                "live_connecting": "Connecting",
                "run_pulse_eyebrow": "Run Pulse",
                "run_state_eyebrow": "Run State",
                "active_agents_label": "Active Agents",
                "requested_label": "Requested",
                "effective_label": "Effective",
                "live_agents_label": "Live Agents",
                "export_zip": "Export ZIP",
                "empty": "No analysis records yet. Start an analysis from the project page.",
                "progress": "Overall Progress",
                "concurrency": "Actual Concurrency",
                "slot_usage": "Slot Usage",
                "current_facet": "Current Facet",
                "queued_facets": "Queued Facets",
                "latest_event": "Latest Event",
                "completed": "Completed",
                "running": "Running",
                "queued": "Queued",
                "failed": "Failed",
                "llm_success": "LLM Success",
                "llm_fallback": "LLM Fallback",
                "input_tokens": "Input Tokens",
                "output_tokens": "Output Tokens",
                "total_tokens": "Total Tokens",
                "facet_queue": "Facet Queue",
                "event_stream": "Event Stream",
                "result_title": "Analysis Results",
                "rerun": "Rerun Facet",
                "no_events": "No Events",
                "no_evidence": "No Evidence",
                "no_conflicts": "No Conflicts",
                "live_output": "Live Output",
                "trace": "LLM Trace",
                "notes": "Notes & Conflicts",
                "evidence": "Evidence",
                "queue_position": "Queue Position",
                "last_updated": "Last Updated",
                "waiting": "Waiting",
                "no_active_agents": "No active agents yet.",
                "inspect_event_stream_summary": "Inspect raw event stream and live diagnostics",
                "open_assets": "Go to Assets",
            },
            "assets": {
                "title": "Asset Generator Console",
                "eyebrow": "Asset Output Workspace",
                "hero_note": "Generate Skill or Persona reports based on analysis results, view streaming output, and edit drafts and versions.",
                "generator_title": "Generate Draft",
                "generator_note": "Prefers streaming generation, automatically switching to draft editor upon completion.",
                "generate": "Start Generation",
                "regenerate": "Regenerate",
                "draft_title": "Draft Editor",
                "versions_title": "Version History",
                "empty_draft": "No drafts yet. Complete analysis to generate assets.",
                "empty_versions": "No published versions yet.",
                "stream_title": "Live Output",
                "status_idle": "Idle",
                "status_running": "Generating",
                "status_completed": "Completed",
                "status_failed": "Failed",
                "field_markdown": "Markdown",
                "field_json": "JSON Payload",
                "field_prompt": "Prompt Text",
                "field_notes": "Notes",
                "prompt_locked_hint": "The actual Skill prompt now follows Skill_merge.md, syncing with the Markdown above.",
                "publish": "Publish Version",
                "save_draft": "Save Draft",
                "view_playground": "Open Playground",
                "view_analysis": "Back to Analysis",
                "stream_hint": "Streaming content will automatically populate the draft editor below.",
                "fallback_hint": "If streaming fails, it will automatically fallback to standard generation.",
                "draft_exports_title": "Export Draft",
                "version_exports_title": "Export Version",
                "export_bundle": "Export ZIP",
                "export_skill_doc": "Skill.md",
                "export_personality_doc": "personality.md",
                "export_memories_doc": "memories.md",
                "export_merge_doc": "Skill_merge.md",
            },
            "playground": {
                "title": "Playground Verification",
                "eyebrow": "Immersive Chat Verification",
                "hero_note_ready": "Test the newly published Skill and persona, observing tone, stance, and detail consistency.",
                "hero_note_missing": "No published Skill available. Cannot enter the playground yet.",
                "empty_turns": "Playground environment is ready. Send your first message to begin verification.",
                "send": "Send",
                "placeholder": "Type what you want to say to the persona. Press Enter to send, Shift + Enter for a new line.",
                "publish_first": "Please publish a Skill version in the Assets page first.",
                "system_notice": "System Notice",
                "you": "You",
                "version_label": "Current Skill Version",
            },
            "preprocess": {
                "title": "Preprocess Workspace",
                "eyebrow": "Preprocess Workspace",
                "hero_note": "Use @filename to reference corpus for preprocessing, retrieval, transformation, sampling, and temporary artifact generation.",
                "sessions": "Sessions",
                "new_session": "New Session",
                "rename_session": "Rename",
                "delete_session": "Delete Session",
                "documents": "Documents",
                "artifacts": "Artifacts",
                "composer_placeholder": "Type your question or use @filename to specify documents. Press Enter to send, Shift + Enter for new line.",
                "composer_hint": "Supports multi-document context, retrieval, Python transformation, and artifact exports.",
                "untitled_session": "Untitled Session",
                "artifact_empty": "No artifacts in this session yet.",
                "document_empty": "No documents available to reference in this project.",
                "send": "Send",
                "sending": "Sending...",
                "working": "Processing...",
                "ready_context": "Preparing Context",
                "rename_prompt": "Enter new session title",
                "execution_failed": "Execution Failed",
                "connection_interrupted": "Connection Interrupted",
                "mention_insert": "Insert",
                "mention_empty": "No matching documents",
            },
            "settings": {
                "title": "Settings",
                "eyebrow": "Model & Service Config",
                "hero_title": "Configure Chat LLM and Embedding Services",
                "hero_note": "Supports official OpenAI, xAI, Gemini endpoints, and custom OpenAI-compatible services. Chat LLM also supports Responses API and Chat Completions API.",
                "chat_panel": "Chat LLM",
                "embedding_panel": "Embedding Model",
                "provider": "Provider",
                "api_mode": "API Mode",
                "base_url": "Base URL",
                "api_key": "API Key",
                "model": "Model Name",
                "save_chat": "Save Chat Config",
                "save_embedding": "Save Embedding Config",
                "discover_models": "Discover Models",
                "discover_loading": "Fetching model list...",
                "discover_empty": "No available models returned from the service.",
                "discover_failed": "Model discovery failed",
                "discover_result": "Model List",
                "hint_openai": "Leave empty to automatically use the official OpenAI endpoint https://api.openai.com/v1",
                "hint_xai": "Leave empty to automatically use the official xAI endpoint https://api.x.ai/v1",
                "hint_gemini": "Leave empty to automatically use the official Gemini OpenAI-compatible endpoint",
                "hint_custom": "Custom OpenAI Compatible services must specify a Base URL.",
                "placeholder_openai": "Leave empty to use official OpenAI endpoint",
                "placeholder_xai": "Leave empty to use official xAI endpoint",
                "placeholder_gemini": "Leave empty to use official Gemini compatible endpoint",
                "placeholder_custom": "e.g., https://api.example.com/v1",
                "model_placeholder": "Enter manually or click 'Discover Models' to auto-detect",
                "hero_label": "Config Matrix",
                "hero_chip_chat": "Chat Matrix",
                "hero_chip_embedding": "Embedding Routing",
                "hero_chip_active": "Active First",
                "hero_chip_fallback": "Ordered Fallback",
                "hero_stat_configs": "Config Slots",
                "hero_stat_providers": "Provider Types",
                "hero_stat_services": "Service Channels",
                "service_chat_eyebrow": "Chat Orchestration",
                "service_embedding_eyebrow": "Embedding Routing",
                "service_chat_summary": "Organize multiple Chat endpoints into a primary/fallback chain and switch providers or API modes faster.",
                "service_embedding_summary": "Maintain a resilient primary/fallback chain for embedding services so retrieval stays available.",
                "config_unit": "slots",
                "save_order": "Save Order",
                "add_config": "Add Config",
                "sequence_title": "Config Pages",
                "page_sequence_note": "Use the paging cards to switch configs. The current order is the fallback order.",
                "selected_config": "Editing",
                "previous": "Previous",
                "next": "Next",
                "config_count": "Config Count",
                "active_config": "Current Active",
                "fallback_count": "Fallback Count",
                "provider_coverage": "Provider Coverage",
                "move_up": "Move Up",
                "move_down": "Move Down",
                "delete_config": "Delete Config",
                "config_name": "Config Name",
                "fallback_note": "Fallback Note",
                "fallback_active": "Current primary config",
                "fallback_ordered": "Participates in fallback by current order",
                "model_select": "Model Select",
                "model_override": "Manual Override",
                "save_and_sync": "Save & Sync Models",
                "save_sync_hint": "Saving immediately refreshes the discovered model list for this config.",
                "models_discovered": "Models Found",
                "order_position": "Order Position",
                "active_status": "ACTIVE",
                "fallback_status": "FALLBACK",
                "model_select_placeholder": "Save to auto-fetch model list",
                "notice_added": "Added a new empty config. Fill it in and save when ready.",
                "notice_switched": "Active config switched. Save the config if you want to sync its model list.",
                "notice_reordered": "Config order updated.",
                "notice_removed": "Config removed.",
                "notice_saving": "Saving settings...",
                "notice_syncing": "Saving and syncing models...",
                "notice_saved": "Saved the current order and active config.",
                "notice_synced": "Saved and refreshed the model list.",
                "notice_sync_failed_prefix": "Saved, but model sync failed: ",
                "notice_save_failed": "Save failed.",
            },
            "telegram_preprocess": {
                "title": "Telegram Preprocess",
                "hero_title": "Telegram Preprocess Console",
                "hero_note": "After importing structured JSON, real-time SQL materialization, weekly summary concurrency, topic precipitation, and intermediate artifact status will be displayed here.",
                "concurrency_label": "Weekly Summary Concurrency",
                "btn_resume": "Resume Preprocess",
                "btn_start": "Start Preprocess",
                "stage_waiting": "Waiting to start",
                "live_note": "Real-time monitoring of SQL materialization, weekly summaries, and final topic writing progress.",
                "status_waiting": "Waiting for tasks",
                "overall_progress": "Overall Progress",
                "coverage_progress": "Weekly Summary Coverage",
                "current_run": "Current Run",
                "stage": "Stage",
                "total_progress": "Total Progress",
                "weekly_candidates": "Weekly Candidates",
                "final_topics": "Final Topics",
                "request_concurrency": "Request Concurrency",
                "active_workers": "Active Workers",
                "completed_weeks": "Completed Weeks",
                "remaining_weeks": "Remaining Weeks",
                "no_run": "No preprocess run yet",
                "worker_lanes": "Worker Lanes",
                "no_workers": "No active workers yet.",
                "trace_timeline": "Subagent Timeline",
                "waiting_events": "Waiting for task events.",
                "live_output": "Current LLM Output",
                "waiting_llm": "Waiting for new LLM request to start.",
                "empty_weekly": "Current Run has no weekly candidate results yet.",
                "empty_top": "Current Run has no Top Users results yet.",
                "empty_active": "Current Run has no active users results yet.",
                "topic_table": "Weekly Topics Table",
                "empty_topics": "Current Run has no final topic results yet.",
                "history_run": "History Runs",
                "empty_history": "No historical preprocess records yet."
            },
            "skill": {
                "preview": "Skill Preview",
                "draft_title": "Skill Draft",
                "hero_note": "Generate draft from latest analysis, edit and publish as a formal version.",
                "regenerate": "Regenerate Draft",
                "back_to_analysis": "Back to Analysis",
                "draft_eyebrow": "Draft",
                "edit_draft": "Edit Draft",
                "review_notes": "Review Notes",
                "save_draft": "Save Draft",
                "publish_version": "Publish Version",
                "no_draft": "No draft available. Wait for analysis to complete before generating Skill.",
                "version_history": "Version History",
                "published_versions": "Published Versions",
                "published": "Published",
                "no_versions": "No published versions yet."
            }
        }
    }
}

def page_strings(page_name: str, locale: str = DEFAULT_LOCALE) -> dict[str, Any]:
    if locale not in LOCALES:
        locale = DEFAULT_LOCALE
    
    locale_data = LOCALES[locale]
    page = deepcopy(locale_data["page"].get(page_name, {}))
    return {
        "locale": locale,
        "common": deepcopy(locale_data["common"]),
        **page,
    }
